/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_documents__document_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/golden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Golden */
        get: operations["get_golden_documents__document_id__golden_get"];
        /**
         * Put Golden
         * @description Stores a reviewer's correction; it becomes the document's golden label.
         */
        put: operations["put_golden_documents__document_id__golden_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ocr */
        get: operations["get_ocr_documents__document_id__ocr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_documents__document_id__pages__page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_documents__document_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evals */
        get: operations["list_evals_evals_get"];
        put?: never;
        /** Start Eval */
        post: operations["start_eval_evals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_evals_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval */
        get: operations["get_eval_evals__eval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_evals__eval_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prompts */
        get: operations["prompts_prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schemas */
        get: operations["list_schemas_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_schemas__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /** File */
            file: string;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            golden?: components["schemas"]["GoldenOut"] | null;
            /** Has Golden */
            has_golden: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_run?: components["schemas"]["RunSummary"] | null;
            /** Mime */
            mime: string;
            /** Name */
            name: string;
            /** Ocr Status */
            ocr_status: string;
            /** Ocr Text */
            ocr_text: string | null;
            /** Page Count */
            page_count: number;
            /** Pages */
            pages: components["schemas"]["PageOut"][];
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            /** Source */
            source: string;
            /** Split */
            split: string | null;
        };
        /** DocumentList */
        DocumentList: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
            /** Total */
            total: number;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Has Golden */
            has_golden: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_run?: components["schemas"]["RunSummary"] | null;
            /** Mime */
            mime: string;
            /** Name */
            name: string;
            /** Ocr Status */
            ocr_status: string;
            /** Page Count */
            page_count: number;
            /** Source */
            source: string;
            /** Split */
            split: string | null;
        };
        /** EvalOut */
        EvalOut: {
            /** Cost Per Doc */
            cost_per_doc?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Doc Count */
            doc_count: number;
            /** Doc Exact Rate */
            doc_exact_rate?: number | null;
            /** Effort */
            effort: string;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
            /** Failed */
            failed: number;
            /** Fewshot K */
            fewshot_k: number;
            /** Field Order */
            field_order?: string[];
            /** Finished At */
            finished_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lenient Accuracy */
            lenient_accuracy?: number | null;
            /** Lists */
            lists: {
                [key: string]: unknown;
            };
            /** Mode */
            mode: string;
            /** Model */
            model: string;
            /** Notes */
            notes: string;
            /** Overall Accuracy */
            overall_accuracy?: number | null;
            /** P50 Ms */
            p50_ms?: number | null;
            /** P95 Ms */
            p95_ms?: number | null;
            /** Per Field */
            per_field: {
                [key: string]: unknown;
            };
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Reps */
            reps: number;
            /**
             * Schema Id
             * Format: uuid
             */
            schema_id: string;
            /** Split */
            split: string;
            /** Status */
            status: string;
            /** Succeeded */
            succeeded: number;
            /** Truncated */
            truncated: number;
            /** Use Ocr Text */
            use_ocr_text: boolean;
            /** Value Accuracy */
            value_accuracy?: number | null;
        };
        /** EvalRequest */
        EvalRequest: {
            /** Effort */
            effort?: string | null;
            /** Fewshot K */
            fewshot_k?: number | null;
            /** Limit */
            limit?: number | null;
            /**
             * Mode
             * @default sync
             */
            mode: string;
            /** Model */
            model?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Prompt
             * @default v1
             */
            prompt: string;
            /**
             * Reps
             * @default 1
             */
            reps: number;
            /**
             * Schema Name
             * @default receipt
             */
            schema_name: string;
            /**
             * Split
             * @default test
             */
            split: string;
            /** Use Ocr Text */
            use_ocr_text?: boolean | null;
        };
        /** EvalResultOut */
        EvalResultOut: {
            /** All Correct */
            all_correct?: boolean | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /**
             * Extraction Run Id
             * Format: uuid
             */
            extraction_run_id: string;
            /** Outcomes */
            outcomes?: {
                [key: string]: unknown;
            } | null;
            /** Rep */
            rep: number;
            /** Status */
            status: string;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /** Effort */
            effort?: string | null;
            /** Fewshot K */
            fewshot_k?: number | null;
            /** Model */
            model?: string | null;
            /**
             * Prompt
             * @default v1
             */
            prompt: string;
            /**
             * Schema Name
             * @default receipt
             */
            schema_name: string;
            /** Use Ocr Text */
            use_ocr_text?: boolean | null;
        };
        /** FieldMetaOut */
        FieldMetaOut: {
            /** Children */
            children?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /** Matcher */
            matcher: string;
            /** Path */
            path: string;
            /** Type */
            type: string;
        };
        /** GoldenIn */
        GoldenIn: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** GoldenOut */
        GoldenOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Source */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelOut */
        ModelOut: {
            /** Id */
            id: string;
            /** Input Per Mtok */
            input_per_mtok?: number | null;
            /** Output Per Mtok */
            output_per_mtok?: number | null;
            /** Provider */
            provider: string;
        };
        /** OcrSpanOut */
        OcrSpanOut: {
            /** Box */
            box: number[];
            /** Conf */
            conf: number;
            /** Page */
            page: number;
            /** Text */
            text: string;
            /** Words */
            words?: components["schemas"]["OcrWordOut"][];
        };
        /** OcrWordOut */
        OcrWordOut: {
            /** Box */
            box: number[];
            /** Conf */
            conf: number;
            /** Text */
            text: string;
        };
        /** PageOut */
        PageOut: {
            /** Height */
            height: number;
            /** Page */
            page: number;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /** PromptOut */
        PromptOut: {
            /** Consistency Check */
            consistency_check: boolean;
            /** Fewshot K */
            fewshot_k: number;
            /** Name */
            name: string;
            /** Notes */
            notes: string;
            /** Use Evidence */
            use_evidence: boolean;
            /** Use Ocr Text */
            use_ocr_text: boolean;
        };
        /** RunOut */
        RunOut: {
            /** Boxes */
            boxes?: {
                [key: string]: number[][];
            } | null;
            /** Cache Read Tokens */
            cache_read_tokens?: number | null;
            /** Cache Write Tokens */
            cache_write_tokens?: number | null;
            /** Confidences */
            confidences?: {
                [key: string]: number;
            } | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Effort */
            effort: string;
            /** Error */
            error?: string | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            } | null;
            /** Fewshot Document Ids */
            fewshot_document_ids?: string[] | null;
            /** Fewshot K */
            fewshot_k: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /**
             * Repair Rounds
             * @default 0
             */
            repair_rounds: number;
            /** Request Id */
            request_id?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Schema Id
             * Format: uuid
             */
            schema_id: string;
            /** Served Model */
            served_model?: string | null;
            /** Status */
            status: string;
            /** Use Ocr Text */
            use_ocr_text: boolean;
        };
        /** RunSummary */
        RunSummary: {
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Effort */
            effort: string;
            /** Error */
            error?: string | null;
            /** Fewshot K */
            fewshot_k: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
            /** Use Ocr Text */
            use_ocr_text: boolean;
        };
        /** SchemaOut */
        SchemaOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fields */
            fields: components["schemas"]["FieldMetaOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Json Schema */
            json_schema: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** TaskAccepted */
        TaskAccepted: {
            /**
             * Status
             * @default queued
             */
            status: string;
            /** Task Id */
            task_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_documents_documents_get: {
        parameters: {
            query?: {
                split?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_documents__document_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_golden_documents__document_id__golden_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_golden_documents__document_id__golden_put: {
        parameters: {
            query?: {
                schema_name?: string;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ocr_documents__document_id__ocr_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcrSpanOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_documents__document_id__pages__page__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_documents__document_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evals_evals_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_eval_evals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_evals_compare_get: {
        parameters: {
            query: {
                ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_evals__eval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_evals__eval_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    prompts_prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"][];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schemas_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaOut"][];
                };
            };
        };
    };
    get_one_schemas__name__get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
