version: 2
updates:
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: monthly
    groups:
      web-dependencies:
        patterns: ['*']
    ignore:
      - dependency-name: typescript
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: monthly
